### ISSUE TITLE
deploy did not work with free plan

### ISSUE THREAD

**Issue by matthiasballreich** [swanson/stringer#402]
delpoying on heroku did not work with a free plan anymore, because on a free plan cronjobs are not allowed. i get error message that i should enter my credit card details :/

**Comment by Koronen** [comment]
My instance runs perfectly fine on the free plan and I haven't paid anything for it yet. However, I believe I also had to enter my credit card details back when I created my instance, in order to enable cronjobs. I think it's so they _can_ charge you if your cronjobs use up more resources than what is allowed for on the free plan, not that they necessarily _will_.

https://devcenter.heroku.com/articles/scheduler

**Comment by matthiasballreich** [comment]
mhh okay, so i have to ask them if it is possible to deploy without credit card dteails, because i have no credit card. thanks.

**Comment by duenni** [comment]
Or you coud use OpenShift.

**Comment by matthiasballreich** [comment]
thanks i tried it on openshift. works now!
