### ISSUE TITLE
Farewarning, I got a crazy bill from Heroku today.

### ISSUE THREAD

**Issue by queuebit** [swanson/stringer#415]
No idea what the problem is, but I am shutting down my app for the time being.

[heroku bill](http://imgur.com/cGf1QXz)

**Comment by queuebit** [comment]
I feel a bit better. <whew>

It seems to be a [Heroku billing issue](https://status.heroku.com/incidents/854).

**Comment by zlogic** [comment]
This freaked me out too, especially since the crazy billing started right after I changed the scheduler a bit added a worker dyno in PR https://github.com/swanson/stringer/pull/412

**Comment by swanson** [comment]
Thanks for reporting, will close unless we determine the billing is unrelated to that issue :)

**Comment by zlogic** [comment]
This was indeed caused by the the "scheduler" issue.
After reviewing Heroku terms, it appears that their scheduler addon can actually result in charges even on free plans.
They consider the scheduler to be a separate dyno which is billed regularly, but is refunded up to $34.50 (one month of continuous operation). So to have scheduler addons, a credit card is needed and if jobs consume too much time, this will also lead to cost overruns.

Perhaps it would make sense to use a worker instead of a scheduler?

`while true; do bundle exec rake fetch_feeds; bundle exec rake cleanup_old_stories sleep 9000; done`

This would require no configuration, avoid using the potentially paid addon and also reduce the load on Heroku servers since it won't run while a dyno is sleeping.
