### ISSUE TITLE
Update VPS docs for Ruby 2.3.0

### ISSUE THREAD

**Issue by swanson** [swanson/stringer#421]
https://github.com/swanson/stringer/blob/master/docs/VPS.md

**Comment by duenni** [comment]
For "autostarting" stringer on distros with `systemd` you would do the following:

use foremans export feature to create a systemd target
`foreman export systemd /etc/systemd/system/ -a stringer -u stringer`

enable this target
`systemctl daemon-reload`
`systemctl enable stringer.target`

start it
`systemctl start stringer.target`

There is no need to use `foreman start` after this. stringer is now a systemd service and will start when the server boots up. `foreman` can export to various other formats ([link] (https://ddollar.github.io/foreman/#EXPORT-FORMATS)) so I think this approach is similar for distros using other init systems.
There should also a be a doc to explain how to use apache/nginx or $webserver to reverse proxy to stringer to get it run on port 80 instead of 5000. Did not figure this out yet.

**Comment by vcavallo** [comment]
> There should also a be a doc to explain how to use apache/nginx or $webserver to reverse proxy to stringer to get it run on port 80 instead of 5000. Did not figure this out yet.

This is still true. the VPS docs currently leave off recommending running `foreman start` and then proceed to some glued-on nginx config that doesn't exactly map to the previous instructions.
