### ISSUE TITLE
Heroku row limit is triggered too often

### ISSUE THREAD

**Issue by danse** [swanson/stringer#471]
I have an old version of Stringer installed, not sure where to find the version on the repo but it's from 2014. i have a bunch of unread stories, they could be 20, but i get repeated warnings from Heroku about approaching the limit and disruption imminent. i don't want my stringer instance to be disrupted!

i would run the cleanup command and then receive the same warning again, at intervals that seem random, sometimes a month, sometimes a few days. maybe there is some known bug which seems to consume way more database rows that i could expect in my case. i could try to update to a newer version, any hints about how to update keeping the data?

**Comment by gabrielpoca** [comment]
Hi @danse ! I'm sorry to hear that. I was running my instance for more than one year before it complained once about the limit. I think the next step would be to upgrade.  You could start by making a backup of your current system, worst case scenario you can restore from it. You could also export the feeds opml file. It also seems that there have been only [two migration](https://github.com/swanson/stringer/tree/master/db/migrate) since 2014, and they look harmless. I think the upgrade should be fine.

**Comment by danse** [comment]
Cool, thanks for the hints!
